# All these field is serialized into the meta property of the ROM
name="Survivors"
author="sigmasoldi3r"
desc="A survival game in natural environments"
site="http://github.com/sigmasoldi3r"
version="1.0.0"

# You can add any extra metadata you wish, it will be stored
# into the ROM and can be read by scripts later.
[extra]
test="Yay! I'm a test variable!"
# Note: It does not require to be under [extra], you can place it
# wherever you want.

# The manifest part is an optional, reserverd part that aims
# to declare special information about the game, like the kind
# of storage (Eg: Profile vs Saved game vs Arcade).
[manifest]
storage="save"
